name: Release

on:
  push:
    branches:
      - "main"
      - "next"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: oven-sh/setup-bun@v1

      - name: Run semantic release
        run: |
          bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
